spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arsenal?serverTimezone=UTC
    username: root
    password: 17171717
    platform: mysql
    continue-on-error: true
    initialization-mode: always
  jpa:
    show-sql: true