spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shield?serverTimezone=UTC
    username: root
    password: rq5425809
    platform: mysql
    continue-on-error: true
    initialization-mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect