spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shield?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: rq5425809
    platform: mysql
    continue-on-error: true
    initialization-mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  session:
    store-type: redis
    #会话超时。如果未指定持续时间后缀，则使用秒。
    timeout: 18000
    redis:
      #ON_SAVE和IMMEDIATE
      flush-mode: ON_SAVE
      #用于存储Session的命名空间
      namespace: spring:session
server:
  port: 8079