#application.yml模板
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dev?useSSL=false
    username: root
    password: dbpass
    #当执行schema.sql的用户不同时可以配置以下两项
    schema-username: root
    schema-password: dbpass
    #当执行data.sql的用户不同时可以配置以下两项
    data-username: root
    data-password: dbpass
    platform: mysql
    schema: classpath:schema.sql
    data: classpath:data.sql
    continue-on-error: true
    initialization-mode: always