spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shield?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 17171717
    platform: mysql
    continue-on-error: true
    initialization-mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8079
jwt:
  secret: 2g3q6f&jZmvNV6KT!&5E11udkRbbH!LZ